### ISSUE TITLE
Close menu

### ISSUE THREAD

**Issue by ludwici** [MarioS271/quick_commands_mod#4]
Hello
It's not a problem, just idea. I suggest allowing you to close the menu by pressing the F8 button. Now I need to press F8, and press escape (if I haven’t selected anything). It was more convenient to be able to immediately close the menu without having to reach for the escape button

**Comment by MarioS271** [comment]
Thank you for the idea! I'll implement it soon with some other things, as I'm also thinking about giving the player some options to always have the client night vision enabled as soon as they load into a world, and for them to not loose the night vision on respawn. Also, I want the game to remember in what worlds and servers the night vision was enabled, and re-enable it as soon as you join there.
But enough yapping from me, thanks for that idea! Working on it! 😊
